### ISSUE TITLE
Engine doesn't fully analyze certain positions

### ISSUE THREAD

**Issue by nmrugg** [hxim/simplechessboard#1]
If you paste in this position `r2k4/3br2p/pppN4/1PB3P1/8/1n3pb1/P1P1NP1P/R4R1K w - - 0 27`, it will only give the analysis for one move.

![simplechess](https://user-images.githubusercontent.com/387105/31926833-ad24b5c2-b8c3-11e7-9ff9-eadb4e3a7b5e.jpg)

**Comment by hxim** [comment]
Thank you for your bug report i fix this problem in version 1.3 https://github.com/hxim/simplechessboard/commit/0e090ebc7b42cdaa3a5ffd3f888e70101b11342d
